{{- if .Values.notificationWorker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vitasync.fullname" . }}-notification-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vitasync.notificationWorker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.notificationWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "vitasync.notificationWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.notificationWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "vitasync.notificationWorker.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "vitasync.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "vitasync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.notificationWorker.podSecurityContext | nindent 8 }}
      containers:
        - name: notification-worker
          image: {{ include "vitasync.worker.image" . }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.notificationWorker.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "vitasync.configMapName" . }}
            - secretRef:
                name: {{ include "vitasync.secretName" . }}
          env:
            - name: WORKER_QUEUES
              value: "notifications"
            {{- with .Values.notificationWorker.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.notificationWorker.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.notificationWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.notificationWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
