{{- if and .Values.ingress.admin.enabled .Values.ingress.admin.rateLimit.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-admin-rate-limit
  namespace: {{ .Release.Namespace }}
spec:
  rateLimit:
    average: {{ .Values.ingress.admin.rateLimit.average }}
    burst: {{ .Values.ingress.admin.rateLimit.burst }}
    period: {{ .Values.ingress.admin.rateLimit.period | quote }}
{{- end }}
