apiVersion: 1

deleteDatasources: []

datasources:
  - name: VitaSync PostgreSQL
    type: postgres
    uid: vitasync-pg
    url: ${PG_HOST}:${PG_PORT}
    user: ${PG_USER}
    database: ${PG_DATABASE}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: false
    version: 1
